[mypy]
python_version = 3.11
warn_return_any = true
warn_unused_configs = true
plugins = sqlalchemy.ext.mypy.plugin
cache_dir = /tmp/.mypy_cache

[mypy-jose.*]
ignore_missing_imports = true

[mypy-celery.*]
ignore_missing_imports = true

[mypy-pythemis.*]
ignore_missing_imports = true
